main page action panel and logo
micahkatz/cs4485-tutoring-website pull request #1
Opened 2023-03-03 22:23 UTC by GoldenJ19

2023-03-07 21:21 UTC, micahkatz requested changes
In general see if you can move everything to be in tailwind

2023-03-07 21:21 UTC, micahkatz commented on src/components/ActionPanel.tsx
> +                    <img src="next_appointment.svg" className="action-panel-image"/>
There is a `react-icons` library where you can load these images from. https://react-icons.github.io/react-icons/

This one should be called `IoCalendarClearOutline`

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
> +    max-width:112px;
You should probably put max width on the container but not the images themselves. You can do this with the `max-w` class

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
> +    height: 112px;
You can also do this with the `h-...` class

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
> +    @apply m-auto;
Once you have finished the tailwind conversions you can move the `@apply`s out of here

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
> +    height: 192px;
same here with `height`

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
> +    top: 50%;
see if there is a better way to center without using `position: absolute` and maybe use flexbox to center it. See if you can do it in tailwind

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
>    background: var(--color-background)
this is the same as `bg-background` i believe

2023-03-07 21:21 UTC, micahkatz commented on src/styles/globals.css
>    background: var(--color-background)
for tailwind I mean

2023-03-09 07:47 UTC, GoldenJ19 commented
Made changes you suggested, and resolved conflicts. This PR is ready for merge, and is waiting on approval by you.

2023-03-09 20:57 UTC, micahkatz approved these changes

2023-03-09 20:58 UTC, merged