Tutor upgrade implemented
micahkatz/cs4485-tutoring-website pull request #30
Opened 2023-04-28 03:03 UTC by GoldenJ19

2023-04-30 19:47 UTC, micahkatz requested changes

2023-04-30 19:47 UTC, micahkatz commented on src/pages/account.tsx
> +                                <button
Put a popup with `confirm()` that will ask "Are you sure you want to become a tutor? This change is irreversable"

2023-05-03 11:17 UTC, GoldenJ19 commented
Changes made, the many commits you see was a result of a rebase with main. I was just too lazy to squash the commits :x

2023-05-04 20:03 UTC, micahkatz approved these changes

2023-05-04 20:03 UTC, merged